# Generated by Django 4.0.1 on 2022-07-26 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trans', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='account_balance',
            field=models.IntegerField(default=0),
        ),
    ]
