# Generated by Django 4.0.1 on 2022-07-23 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="is_seller",
        ),
        migrations.RemoveField(
            model_name="user",
            name="is_verified",
        ),
    ]
